bare bones simple trip model.
dd-harp/MASH pull request #13
Opened 2020-04-25 00:32 UTC by slwu89

This uses the API in "continuous_step.R" to build a bare-bones "simple trip" model that runs. I made a new vignette in "simpletrip.Rmd" to explain it. This is all very much a work in progress but I think this is a good point to open a PR because as a result of learning/interacting with the `continuous_step` API I found and fixed a few small bugs.

Next steps are to make rigorous the comparison of analytic vs. simulated results in the vignette and provide more helper functions for the simple trip module. After that I think we can get rid of this branch.

2020-04-27 19:30 UTC, adolgert requested changes
Hey, great! I have a couple of requested syntax changes. The model you wrote is the most important part, and that looks good.

2020-04-27 19:30 UTC, adolgert commented on macro/R/continuous_step.R
> +  if(is.null(simulation$observer)){
Could you put spaces around the condition, so `if (is.null...rver)) {`? Is that part of the standard?

2020-04-27 19:30 UTC, adolgert commented on macro/R/continuous_step.R
> +    observer <- simulation$observer
This is going to sound silly, but I'll share it because it's a software engineering standard: We match if and else, when possible. Studies of software defects show that missing else clauses are a major source of defects, so we either put the `observer <-...` into an else clause or annotate why an if is missing an else. Rules like this are in a book called _Code Complete._ It discusses design, down to the syntax level.

2020-04-27 19:30 UTC, adolgert commented on macro/R/continuous_step.R
> +      trajectory <- c(trajectory,replicate(n=trajectory_cnt,expr={NULL}))
What does this do differently?

2020-04-27 19:30 UTC, adolgert commented on macro/tests/testthat/test-flux-movement.R
> +# test_that("markov_flow initializes", {
Please don't check this in this way. You'll mess up my by-line edits.

2020-04-27 19:30 UTC, adolgert commented on macro/tests/testthat/test-flux-movement.R
> +# test_that("markov_flow initializes", {
I mean, just don't merge the PR with this change. I'd have to back it out.

2020-04-27 19:30 UTC, adolgert commented on macro/R/simpletrip.R
> +#   April 2020
This is in the git record. And, for shared code, it gets confusing quickly about how to update these kinds of headers. They used to be common, and we would use the repo to maintain them. Now, I never see them. Sometimes people have a license on each page, but we don't seem to have to do that here.

2020-04-27 19:30 UTC, adolgert commented on macro/R/simpletrip.R
> +#' @return a list
Maybe a list of transitions?

2020-04-27 19:30 UTC, adolgert commented on macro/R/simpletrip.R
> +simple_trip_transitions <- function(){
I did look up the tidyverse style guide, and there is a space before the left-paren. This continues below.

2020-04-27 19:30 UTC, adolgert commented on macro/R/simpletrip.R
> +    is_enabled = function(state,time){
and spaces after commas. The editor should flag these?

2020-04-27 19:30 UTC, adolgert commented on macro/R/simpletrip.R
> +}
This is so succinct. Nice. Maybe limit line length to 100 characters?

2020-04-27 19:30 UTC, adolgert commented on macro/tests/testthat/test-flux-movement.R
> +# test_that("markov_flow initializes", {
And there is a function called skip("message about why skipped") that is how testthat skips tests.

2020-04-27 19:30 UTC, adolgert commented on macro/vignettes/simpletrip.Rmd
> +
Try making a code block here that shows the simple trip transitions. Use an empty code block with the header `{r, code = capture.output(dump("simple_trip_transitions", "")}`

2020-04-29 17:05 UTC, slwu89 commented on macro/tests/testthat/test-flux-movement.R
> +# test_that("markov_flow initializes", {
Sorry, this is my bad. I didn't intend to change this file.

2020-04-29 17:05 UTC, slwu89 commented on macro/R/continuous_step.R
> +      trajectory <- c(trajectory,replicate(n=trajectory_cnt,expr={NULL}))
It makes it more clear what slots in the extended trajectory object are unfilled and there to pre-allocate memory. It's a little jarring to get output from the simulator where some of the events at the end are duplicates of stuff that has "already happened" earlier, and makes it easier to trim down the excess after it runs.

2020-04-29 17:05 UTC, slwu89 commented on macro/R/simpletrip.R
> +#   April 2020
Ok, what should we do then?

2020-04-29 17:06 UTC, slwu89 commented on macro/R/simpletrip.R
> +simple_trip_transitions <- function(){
ok

2020-04-29 17:06 UTC, slwu89 commented on macro/R/simpletrip.R
> +    is_enabled = function(state,time){
ok

2020-04-29 17:06 UTC, slwu89 commented on macro/R/simpletrip.R
> +}
ok

2020-04-29 17:07 UTC, slwu89 commented on macro/vignettes/simpletrip.Rmd
> +
Showing the actual R code that is in the package? I'm a little wary of that as that is supposed to be hidden from users?

2020-04-29 17:07 UTC, slwu89 commented on macro/R/continuous_step.R
> +    observer <- simulation$observer
that makes sense, I'll observe that convention!

2020-04-29 17:08 UTC, slwu89 commented on macro/R/continuous_step.R
> +  if(is.null(simulation$observer)){
sure, will do from now on!

2020-04-29 17:10 UTC, adolgert commented on macro/R/simpletrip.R
> +#   April 2020
Uh, there should be something to put at the top from lawyers. Barring that... either nothing or a message about what this file is about? We can talk this over in the code development meeting, too. This is a feel-good decision.

2020-04-29 17:11 UTC, adolgert commented on macro/vignettes/simpletrip.Rmd
> +
This vignette is such a good demo of how the continuous time system works. That function is nice and short, which is why I thought to include it. That was just a suggestion for presentation. Meh.

2020-04-29 22:48 UTC, adolgert approved these changes
Excellent! It looks so pretty, too. Please merge!

2020-04-29 22:53 UTC, merged